# Generated by Django 3.2.7 on 2021-09-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
